{
 "title": "Gbox420",
 "description": "Grow tent overview",
 "tags": [ "gbox420" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aero",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_modulestate" }
     ]
    },
    {
     "alias": "Hempy",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_hempy_modulestate" }
     ]
    },
    {
     "alias": "Reservoir",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_reservoir_modulestate" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT last(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'gbox420_power1_power') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_power1_power" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Daily energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT first(*) FROM (SELECT spread(\"value\") FROM \"homeassistant\".\"autogen\".\"kWh\" WHERE (\"entity_id\"='gbox420_power1_energy' ) GROUP BY time(1d) fill(null) ORDER BY DESC LIMIT 2) ORDER BY DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_power1_energy" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT Spread(\"value\") FROM \"homeassistant\".\"autogen\".\"kWh\" WHERE (\"entity_id\"='gbox420_power1_energy' ) GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_power1_energy" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Light1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_light1_brightness" }
     ]
    },
    {
     "alias": "Light2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_light2_brightness" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Internal fan",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_internal_fan" }
     ]
    },
    {
     "alias": "Exhaust fan",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_exhaust_fan" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aero tote",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_weight" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Hempy reservoir",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_reservoir_weight" }
     ]
    }
   ]
  },
  {
   "title": "Air temp & humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Internal temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_internal_temp" }
     ]
    },
    {
     "alias": "External temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_external_temp" }
     ]
    },
    {
     "alias": "Internal humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_internal_humidity" }
     ]
    },
    {
     "alias": "External humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_external_humidity" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Internal temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_internal_temp" }
     ]
    },
    {
     "alias": "External temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_external_temp" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Internal humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_internal_humidity" }
     ]
    },
    {
     "alias": "External humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_external_humidity" }
     ]
    }
   ]
  },
  {
   "title": "Aero pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "yaxes": [
    { "format": "pressurebar" }
   ],
   "targets": [
    {
     "alias": "Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_pressure" }
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_minpressure" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_maxpressure" }
     ]
    },
    {
     "alias": "Weight",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_weight" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Tank",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_pressure" }
     ]
    },
    {
     "alias": "Last spray",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_lastspray" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_sprayduration" }
     ]
    },
    {
     "alias": "Day interval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_dayinterval" }
     ]
    },
    {
     "alias": "Night interval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_nightinterval" }
     ]
    }
   ]
  },
  {
   "title": "Hempy bucket 1 weight",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    {
     "alias": "Bucket",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "query": "SELECT mean(\"value\") FROM \"kg\" WHERE (\"entity_id\" = 'gbox420_bucket1_weight') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket1_weight" }
     ]
    },
    {
     "alias": "Dry",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket2_dryweight" }
     ]
    },
    {
     "alias": "Wet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket1_wetweight" }
     ]
    },
    {
     "alias": "Waste",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket1_wasteweight" }
     ]
    }
   ]
  },
  {
   "title": "Hempy bucket 2 weight",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    {
     "alias": "Bucket",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket2_weight" }
     ]
    },
    {
     "alias": "Dry",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket2_dryweight" }
     ]
    },
    {
     "alias": "Wet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket2_wetweight" }
     ]
    },
    {
     "alias": "Waste",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket2_wasteweight" }
     ]
    }
   ]
  },
  {
   "title": "Reservoir",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    {
     "alias": "Water temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_reservoir_watertemp" }
     ]
    },
    {
     "alias": "Reservoir weight",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_reservoir_weight" }
     ]
    },
    {
     "alias": "pH",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_reservoir_ph" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Bucket 1",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket1_state" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Pump 1",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket1_pumpstate" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Bucket 2",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket2_state" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Pump 2",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_bucket2_pumpstate" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aero",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_state" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Pump",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_aero1_pumpstate" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gbox420_lastreport" }
     ]
    }
   ]
  }
 ]
}