#ESPHome YAML configuration file for a Gate or Garage door
#Runs on a Raspberry Pico W  (or any ESPHome supported device with adjustments to the output section)
#When a virtual button (sample in file gateDashoard) is pressed turn on a relay for 1 second using a Relay

esphome:
  name: gate
  friendly_name: Gate
  on_boot:
    priority: 10
    then:
      - output.turn_off: relay

rp2040:
  board: rpipicow

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret gate_encryption_key

ota:
  - platform: esphome
    password: !secret gate_ota_password

wifi:
  #use_address: 192.168.1.2   # Use this IP to upload firmware when changing the device's static IP.
  ssid: !secret gate_wifi_ssid
  password: !secret gate_wifi_password
  power_save_mode: none
  fast_connect: true
  reboot_timeout: 30min
  manual_ip:
    static_ip: 192.168.1.42
    gateway: 192.168.1.1 #Router's IP
    subnet: 255.255.255.0 #Network mask

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "GateHS"
    password: !secret gate_wifi_password

output:
  - platform: gpio # Relay
    pin: GPIO6 # Port controlling the Relay
    id: relay
    inverted: False
  - platform: gpio # Pico W built-in LED
    pin: 32
    id: led

button:
  - platform: template
    id: gate_button
    name: "Gate"
    on_press:
      then:
        - lambda: |-
            ESP_LOGI("Gate", "Gate button was pressed");
        - output.turn_on: led
        - output.turn_on: relay
        - delay: 1s
        - output.turn_off: led
        - output.turn_off: relay

sensor:
  - platform: internal_temperature
    name: "Internal temp"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    update_interval: 60s
    filters:
      - delta: 0.1 # Only update if the change is greater than 0.1 °C
    #  - sliding_window_moving_average:
    #      window_size: 15
    #      send_every: 15
    #   - median:
    #     window_size: 10 #calculate median based on the last 10 readings