esphome:
  name: mainesp
  friendly_name: MainESP

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret mainesp_encryption_key

ota:
  - platform: esphome
    password: !secret mainesp_ota_password

web_server:
  port: 80

wifi:
  ssid: !secret mainesp_wifi_ssid
  password: !secret mainesp_wifi_password
  power_save_mode: none
  fast_connect: true
  reboot_timeout: 30min
  manual_ip:
    static_ip: 192.168.9.111
    gateway: 192.168.9.254 #Router's IP
    subnet: 255.255.255.0 #Network mask

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "MainespHS"
    password: !secret mainesp_wifi_password

captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

# Enable telnet server
stream_server:
  uart_id: uart_bus
  port: 23

output:
  - platform: gpio
    pin: GPIO4
    id: status_led
  - platform: gpio
    pin: GPIO5
    id: serial_led

interval:
  - interval: 2s
    then:
      - output.turn_on: status_led
      - delay: 1s
      - output.turn_off: status_led