# Used in gate.yaml as secrets.yaml  (example: password: !secret gate_ota_password)
# Copy this file to your ESPHome folder as secrets.yaml (or append to it) and update the values.

gate_wifi_ssid: "Your WiFi SSID"
gate_wifi_password: "Your WiFi Password"
gate_encryption_key: "vQ0I7EfC25fTju/41LnKJQFG5DFLZR9m3ggWvfz7eiA=" # 32-byte base64 string - generate here: https://esphome.io/components/api.html
gate_ota_password: "1b4f64be2c81cd424617d1722962f50a" # MD5 hash of any password string (32 characters) - generate here: https://www.md5hashgenerator.com/
