# Used in hempy.yaml as secrets.yaml  (example: password: !secret hempy_ota_password)
# Copy this file to your ESPHome folder as secrets.yaml (or append to it) and update the values.

hempy_wifi_ssid: Your WiFi SSID"
hempy_wifi_password: "Your WiFi Password"
hempy_encryption_key: "VRhEB+y/0ivkXFRwmzwCBJmfyJqDYbxLGYtfxDBQWB0=" # 32-byte base64 string - generate here: https://esphome.io/components/api.html
hempy_ota_password: "4e636683a18c3f8eed093971869236d4990748df" # MD5 hash of any password string (32 characters) - generate here: https://www.md5hashgenerator.com/
