para_wifi_ssid: "Your WiFi SSID"
para_wifi_password: "Your WiFi Password"
para_encryption_key : "2N8hYZqwbZxtLwD7GTGx0xzZk6T7jVLrTqXrT82/c84="   # 32-byte base64 string - generate here: https://esphome.io/components/api.html
para_ota_password : "b366970b0e60ee2f978c384e42c48b5a" # MD5 hash of any password string (32 characters) - generate here: https://www.md5hashgenerator.com/
