para_wifi_ssid: "Your WiFi SSID"
para_wifi_password: "Your WiFi Password"
para_encryption_key: "8M/UwS9/s5/GiV2r5Bi4dKTQncVGOBxft5iN1MObU0k=" # 32-byte base64 string - generate here: https://esphome.io/components/api.html
para_ota_password: "ff1d72d7f6a6295b0646fd68718f82b6" # MD5 hash of any password string (32 characters) - generate here: https://www.md5hashgenerator.com/
